# 站点配置
site:
  title: "DreamBlog"
  author: "BinaryDumplings"
  copyright: "© 2024 BinaryDumplings. All Rights Reserved."
  beian: "津ICP备2024018227号-1"
  beian_url: "https://beian.miit.gov.cn/"

# 社交链接
social:
  github: "https://github.com/DreamChaser-luzeyu"
  email: "mailto:yydluzeyu#gmail.com (replace '#' with '@')"
  # twitter: "https://twitter.com/your-handle"
